# Generated by Django 4.1.6 on 2023-02-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
