# Generated by Django 4.1.6 on 2023-03-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقالات'},
        ),
    ]
