# Generated by Django 4.1.6 on 2023-03-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to='images/profile', verbose_name='تصویر'),
        ),
    ]
